"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var generation_1 = require("../../../modules/lobby/controllers/generation");
var join_1 = require("../../../modules/lobby/controllers/join");
var authenticateJWT_1 = require("../../middleware/authenticateJWT");
var router = express_1.default.Router();
router.get("/generate", authenticateJWT_1.authenticateJWT, generation_1.generateCodeAndLobby);
router.post("/find", authenticateJWT_1.authenticateJWT, join_1.joinLobby);
exports.default = router;
