version: "3.8" # or another version you want to use

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI} # This should work now

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
