"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var index_1 = require("../../../modules/user/controllers/auth/index");
var authenticateJWT_1 = require("../../middleware/authenticateJWT");
var router = express_1.default.Router();
router.post("/login", index_1.authenticateUser);
router.get("/logout", authenticateJWT_1.authenticateJWT, index_1.userLogout);
router.get("/refresh", index_1.getNewAccessToken);
exports.default = router;
